/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBidsRouteImport } from './routes/admin/bids'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminPipelineRouteImport } from './routes/admin/pipeline'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSupplyRouteImport } from './routes/admin/supply'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBidsRoute = AdminBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupplyRoute = AdminSupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/bids': typeof AdminBidsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/supply': typeof AdminSupplyRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/bids': typeof AdminBidsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/supply': typeof AdminSupplyRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/bids': typeof AdminBidsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/supply': typeof AdminSupplyRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/bids'
    | '/admin/companies'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/supply'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/bids'
    | '/admin/companies'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/supply'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/bids'
    | '/admin/companies'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/supply'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bids': {
      id: '/admin/bids'
      path: '/bids'
      fullPath: '/admin/bids'
      preLoaderRoute: typeof AdminBidsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supply': {
      id: '/admin/supply'
      path: '/supply'
      fullPath: '/admin/supply'
      preLoaderRoute: typeof AdminSupplyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBidsRoute: typeof AdminBidsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupplyRoute: typeof AdminSupplyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBidsRoute: AdminBidsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupplyRoute: AdminSupplyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
